Repository GreyMatteOr/refactor-tractor-B, pull requests merged in 2020-09, with the labels that each got.

#22 Create Pantry class. Add test file.
  src/pantry.js
  test/pantry-test.js
Labels: Original Spec, documentation

#23 User class original kj
  src/user.js
  test/user-test.js
Labels: Original Spec, documentation

#47 Retrieve all data from an endpoint
  src/scripts.js
Labels: Fetch, documentation

#51 Scss kj
  dist/index.html
  src/css/base.scss
  src/css/index.scss
  src/css/mixins.scss
  src/css/styles.scss
  src/css/variables.scss
  src/index.html
  src/scripts.js
Labels: DOM Manipulation, Sass, documentation

#50 Separate dom nodes and dom methods into 2 new files.
  src/dom-loader.js
  src/domUpdates.js
  src/index.html
  src/scripts.js
Labels: DOM Manipulation, documentation

#55 Shopping list displaying properly
  src/domUpdates.js
  src/pantry.js
  src/scripts.js
  src/user.js
Labels: documentation

#58 Create Shopping List Functionality on Webpage
  dist/images/shopping-cart-icon.png
  src/css/index.scss
  src/dom-loader.js
  src/domUpdates.js
  src/images/shopping-cart-icon.png
  src/index.html
  src/index.js
  src/pantry.js
  src/scripts.js
  src/user.js
  test/pantry-test.js
Labels: DOM Manipulation, documentation

#60 Begin to create mobile version of app
  dist/images/menu.png
  src/css/index.scss
  src/css/media-queries.scss
  src/images/menu.png
  src/index.html
Labels: Sass, documentation

#59 Spies
  package-lock.json
  src/domUpdates.js
  test/dom-tests.js
Labels: Spies, documentation

#64 Mobile version is coming along
  src/css/index.scss
  src/css/media-queries.scss
  src/index.html
Labels: Requirements, Sass, documentation, enhancement

#62 Sunday: push up for review
  test/dom-tests.js
Labels: Spies, documentation

#63 Create POST functionality when buying shoppinglists
  src/domUpdates.js
  src/pantry.js
  src/scripts.js
Labels: DOM Manipulation, Error Handling, documentation

#65 Post ks
  src/domUpdates.js
  src/fetch-requests.js
  src/scripts.js
Labels: Error Handling, Requirements, documentation, enhancement

#66 Complete spies testing for domUpdates
  test/dom-tests.js
Labels: Spies, documentation

#68 Chai spies
  test/fetch-test.js
  test/recipe-test.js
  test/user-test.js
Labels: Fetch, Spies, documentation

#69 Refactor
  dist/images/down-arrow.png
  src/css/index.scss
  src/css/media-queries.scss
  src/dom-loader.js
  src/domUpdates.js
  src/images/down-arrow.png
  src/index.html
  src/index.js
  src/pantry.js
  src/scripts.js
  test/dom-tests.js
  test/fetch-test.js
  test/pantry-test.js
Labels: documentation

#70 Mobileview ks/kj
  README.md
  src/css/index.scss
  src/css/media-queries.scss
Labels: documentation

#71 Refactor
  src/pantry.js
  src/scripts.js
Labels: DOM Manipulation, Requirements, documentation

#72 Css ks
  README.md
  dist/images/down_arrow.png
  dist/index.html
  src/css/media-queries.scss
  src/domUpdates.js
  src/images/down_arrow.png
  src/index.html
Labels: Sass

#73 Scss refactor kj
  src/css/index.scss
  src/css/media-queries.scss
  src/css/mixins.scss
  src/css/variables.scss
Labels: Requirements, Sass, documentation

#74 Now can tab through cards
  src/css/index.scss
  src/domUpdates.js
  src/index.html
Labels: Sass, documentation
